### ISSUE TITLE
gemgis only officially supports python 3.10

### ISSUE THREAD

**Issue by DManowitz** [opengeos/geospatial#31]
### Environment Information

-   geospatial version: 0.8.0
-   Python version: 3.8
-   Operating System: Windows

### What I Did

gemgis is included as a dependency of this package.  However, according to their [installation instructions](https://gemgis.readthedocs.io/en/latest/getting_started/installation.html), only python 3.10 is supported.  However, geospatial only requires python >= 3.8.

**Comment by giswqs** [comment]
Should I remove gemgis? I would not make geospatial require python 3.10 for now. There are still many users using 3.8 and 3.9

**Comment by DManowitz** [comment]
I would remove gemgis.
