### ISSUE TITLE
error installing with pip from source

### ISSUE THREAD

**Issue by Joaquin-Urruti** [opengeos/geospatial#36]
### Environment Information
-   geospatial version: geospatial-0.9.0
-   Python version: Python 3.9.18
-   Operating System: MACOS-ARM Macbook Pro M2

### Description
I'm trying to instal geospatial with pip because I have an environment with whitebox installed with pip, and some scripts that use both packages.

### What I Did
(wbw) /Users/ju > git clone https://github.com/opengeos/geospatial.git

### Output:
Cloning into 'geospatial'...
remote: Enumerating objects: 815, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 815 (delta 119), reused 141 (delta 102), pack-reused 642
Receiving objects: 100% (815/815), 888.14 KiB | 317.00 KiB/s, done.
Resolving deltas: 100% (431/431), done.
(wbw) /Users/ju > cd geospatial

### 2nd command:
(wbw) /Users/ju/geospatial > pip install .
Processing /Users/ju/geospatial
  Preparing metadata (setup.py) ... done
Collecting bokeh (from geospatial==0.9.0)

### 2nd output
...stuff...
Building wheels for collected packages: geospatial, lightgbm
  Building wheel for geospatial (setup.py) ... done
  Created wheel for geospatial: filename=geospatial-0.9.0-py2.py3-none-any.whl size=4254 sha256=ee0dc2a9f9dda2765267f07e7a66851cfd5e2ca95354c18c102eb69cd9eae247
  Stored in directory: /private/var/folders/xt/0fzdrsd52bj4z2cqvy77d5w00000gn/T/pip-ephem-wheel-cache-broy9lm4/wheels/4b/50/3d/f9922042c3c1dcfcf764bd47b61ea11c3a16e125d8b4426118
  Building wheel for lightgbm (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for lightgbm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      2023-09-22 17:08:33,836 - scikit_build_core - INFO - CMake version: 3.27.4
      *** scikit-build-core 0.5.1 using CMake 3.27.4 (wheel)
      2023-09-22 17:08:33,838 - scikit_build_core - INFO - Build directory: /private/var/folders/xt/0fzdrsd52bj4z2cqvy77d5w00000gn/T/tmp3b8bim10/build
      *** Configuring CMake...
      2023-09-22 17:08:34,809 - scikit_build_core - INFO - Ninja version: 1.11.1
      2023-09-22 17:08:34,810 - scikit_build_core - WARNING - libdir/ldlibrary: /Users/ju/anaconda3/envs/wbw/lib/libpython3.9.a is not a real file!
      2023-09-22 17:08:34,810 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/Users/ju/anaconda3/envs/wbw/lib, ldlibrary=libpython3.9.a, multiarch=darwin, masd=None
      loading initial cache file /var/folders/xt/0fzdrsd52bj4z2cqvy77d5w00000gn/T/tmp3b8bim10/build/CMakeInit.txt
      CMake Deprecation Warning at CMakeLists.txt:35 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- The C compiler identification is AppleClang 14.0.3.14030022
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
      -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
      -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
      -- Found OpenMP_C: -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include
      -- Found OpenMP_CXX: -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include
      -- Found OpenMP: TRUE
      -- Performing Test MM_PREFETCH
      -- Performing Test MM_PREFETCH - Failed
      -- Performing Test MM_MALLOC
      -- Performing Test MM_MALLOC - Success
      -- Using _mm_malloc
      -- Configuring done (0.7s)
      -- Generating done (0.0s)
      -- Build files have been written to: /var/folders/xt/0fzdrsd52bj4z2cqvy77d5w00000gn/T/tmp3b8bim10/build
      *** Building project with Ninja...
      ninja: error: '/opt/homebrew/opt/libomp/lib/libomp.dylib', needed by '/private/var/folders/xt/0fzdrsd52bj4z2cqvy77d5w00000gn/T/pip-install-t663i5f6/lightgbm_e0bfa722f2d44cfcb7590d43f679be92/lib_lightgbm.so', missing and no known rule to make it
      
      *** CMake build failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightgbm
Successfully built geospatial
Failed to build lightgbm
ERROR: Could not build wheels for lightgbm, which is required to install pyproject.toml-based projects

**Comment by giswqs** [comment]
pip is not recommended. Try mamba
https://geospatial.gishub.org/installation/#using-mamba

**Comment by Joaquin-Urruti** [comment]
Thank you very much Dr. Wu. 
I've read that is not recommended to instal with conda after using pip (but it's ok to use pip after conda). 
Do you think in this case it's ok if I mix pip with mamba? 
Kind regards.

**Comment by giswqs** [comment]
When install a package with a lot of dependencies, mamba is recommended. After that, using pip is fine but is not recommended.

**Comment by Joaquin-Urruti** [comment]
Thank you!
