### ISSUE TITLE
error when trying to install geopandas in windows

### ISSUE THREAD

**Issue by GISgeekpro** [opengeos/geospatial#37]
### Environment Information

-   geospatial version: 0.9
-   Python version: 3.9
-   Operating System: Windows 10 (enterprise)

### Description

I followed the necessary steps for installing the geospatial package with combination of conda - mamba. When reaching the step for installing geopandas, I get an error message "could not solve for environment specs, the following packages are incompatible" (please see picture below).

The same issue was present also when to install the package in my personal computer running windows 11. 

I also tried installing installing geopandas using only conda - without installing mamba. 

### What I Did

I run the following commands in git-bash, where in the last one I got the attached traceback message: 

conda create -n geo python=3.9
conda activate geo
conda install -c conda-forge mamba
mamba install geopandas

![geospatial_issue_geopandas_installation](https://github.com/opengeos/geospatial/assets/86127856/efc4f68d-0705-4b7d-b275-fb80f972768b)

**Comment by joaobernardo21** [comment]
I have the same problem

**Comment by giswqs** [comment]
Sorry for the delay. Please try installing geospandas from the conda-forge channel. I works fine on my Windows 11. 

```bash
mamba install geopandas -c conda-forge
```

![image](https://github.com/opengeos/geospatial/assets/5016453/bbca9942-dead-46ab-9a5f-0b13223a6171)
