### ISSUE TITLE
Docker image are not visible for public

### ISSUE THREAD

**Issue by Giangblackk** [opengeos/geospatial#41]
Tthe "Build and publish Docker Image" Github workflow works just fine, and it pushed the built image to `ghcr.io/opengeos/geospatial:latest`.

But it seems that this package is currently not visible to public use, as I can't see any package appear in this link [https://github.com/orgs/opengeos/packages?repo_name=geospatial](https://github.com/orgs/opengeos/packages?repo_name=geospatial).

I think this is due to the misconfiguration in Package setting of the [Open Geospatial Solutions](https://github.com/opengeos) GitHub Organization.
I suggest following this [guide](https://stackoverflow.com/a/72259303) to see if we could make the `geospatial` Docker image visible to public so everyone can benefit from it.

And I also suggest to update the documentation to provide guide for using `geospatial` Docker image.

Best regards,

**Comment by giswqs** [comment]
@Giangblackk Thank you for reporting and providing the instructions. I did not realize that the package settings under an organization is private by default. I have changed it public and added the docker instructions in #42
